version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    env_file:               
      - ./backend/.env      
    ports:
      - "8000:8000"
    volumes:
      - ./backend/app:/app/app
    networks:
      - my_network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    env_file:               
      - ./frontend/.env     
    ports:
      - "3000:3000"
    networks:
      - my_network

networks:
  my_network:
    driver: bridge
